<#
Download Vazirmatn font files referenced by the remote css and generate a local CSS file that points to the downloaded fonts.
Run this script from the repo root (PowerShell):

  .\scripts\fetch-vazirmatn-fonts.ps1

It will create `public/fonts/` and `public/fonts/vazirmatn-local.css`.
#>

$ErrorActionPreference = 'Stop'
$outDir = Join-Path $PSScriptRoot '..\public\fonts'
if(-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }

$remoteCssUrl = 'https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css'
$baseUri = [System.Uri]::new($remoteCssUrl)
Write-Host "Fetching font-face CSS from $remoteCssUrl"
$css = Invoke-RestMethod -Uri $remoteCssUrl -UseBasicParsing

if(-not $css){ Write-Error 'Failed to download remote CSS'; exit 1 }

# find all url(...) occurrences
# extract url(...) matches from the downloaded CSS
$matches = [regex]::Matches($css, 'url\(([^)]+)\)')
# strip surrounding quotes/spaces from matched urls
$urls = $matches | ForEach-Object {
  $v = $_.Groups[1].Value
  $v = $v.Trim()
  if($v.Length -gt 0 -and ($v.StartsWith("'") -or $v.StartsWith('"'))){ $v = $v.Substring(1) }
  if($v.Length -gt 0 -and ($v.EndsWith("'") -or $v.EndsWith('"'))){ $v = $v.Substring(0, $v.Length - 1) }
  $v
} | Select-Object -Unique
if(-not $urls){ Write-Host 'No font urls found in CSS'; exit 0 }

$localFiles = @()
foreach($u in $urls){
    try{
      # resolve relative urls against the remote CSS location
      $resolved = [System.Uri]::new($baseUri, $u).AbsoluteUri
      $name = [System.IO.Path]::GetFileName($resolved)
      $dest = Join-Path $outDir $name
      Write-Host "Downloading $resolved -> $dest"
      Invoke-WebRequest -Uri $resolved -OutFile $dest -UseBasicParsing -TimeoutSec 60
      $localFiles += $name
    } catch {
      Write-Warning "Failed to download $u : $_"
    }
}

if($localFiles.Count -eq 0){ Write-Warning 'No fonts downloaded'; exit 0 }

# generate local CSS
$localCssPath = Join-Path $outDir 'vazirmatn-local.css'
Write-Host "Generating local CSS at $localCssPath"
$sb = [System.Text.StringBuilder]::new()
$sb.AppendLine('/* Generated by scripts/fetch-vazirmatn-fonts.ps1 — references local font files in /fonts */') | Out-Null

# crude grouping by filename hints
foreach($f in $localFiles){
  $weight = '400'
  if($f -match 'Bold|700') { $weight='700' }
  elseif($f -match 'Medium|500') { $weight='500' }
  $sb.AppendLine("@font-face { font-family: 'Vazirmatn'; src: url('/fonts/$f') format('woff2'); font-weight: $weight; font-style: normal; font-display: swap; }") | Out-Null
}

[System.IO.File]::WriteAllText($localCssPath, $sb.ToString())
Write-Host 'Done. Open public/styles.css to ensure @import /fonts/vazirmatn-local.css is present.'
